#
# Copyright 2017-2024 O2 Czech Republic, a.s.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

infra: [".github/*"]
legal: ["license-*", "**/license-*"]
scheme: ["scheme/*"]
tools: ["tools/*"]
example: ["example/*"]
documentation: ["docs/*"]
maven: ["maven/*"]

core: ["core/*"]
direct-core: ["direct/core/*"]
direct: ["direct/*"]
direct-io: ["direct/io-*"]

beam: ["beam/*"]
beam-core: ["beam/core/*"]
beam-io: ["beam/io-*"]

flink: ["flink/*"]
flink-core: ["flink/core/*"]
