jdkVersion = "11"
ignoreFiles = ["**/generated/**"]
ignoreRules = [
  "AutoValueImmutableFields",
  "AutoValueSubclassLeaked",
  "BadImport",
  "BadInstanceof",
  "BigDecimalEquals",
  "ComparableType",
  "DoNotMockAutoValue",
  "EmptyBlockTag",
  "EmptyCatch",
  "EqualsGetClass",
  "EqualsUnsafeCast",
  "EscapedEntity",
  "ExtendsAutoValue",
  "InlineFormatString",
  "InlineMeSuggester",
  "InvalidBlockTag",
  "InvalidInlineTag",
  "InvalidLink",
  "InvalidParam",
  "InvalidThrows",
  "JavaTimeDefaultTimeZone",
  "JavaUtilDate",
  "JodaConstructors",
  "MalformedInlineTag",
  "MissingSummary",
  "MixedMutabilityReturnType",
  "PreferJavaTimeOverload",
  "MutablePublicArray",
  "NonCanonicalType",
  "ProtectedMembersInFinalClass",
  "Slf4jFormatShouldBeConst",
  "Slf4jSignOnlyFormat",
  "StaticAssignmentInConstructor",
  "ThreadPriorityCheck",
  "TimeUnitConversionChecker",
  "UndefinedEquals",
  "UnescapedEntity",
  "UnnecessaryLambda",
  "UnnecessaryMethodReference",
  "UnnecessaryParentheses",
  "UnrecognisedJavadocTag",
  "UnsafeReflectiveConstructionCast",
  "UseCorrectAssertInTests",
  "Slf4jLoggerShouldBeNonStatic"]
