#
# Copyright 2017-2025 O2 Czech Republic, a.s.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      name: repl-controller
    name: repl-controller
  spec:
    ports:
    - port: 4001
      protocol: TCP
      targetPort: 4001
    selector:
      app: repl-controller
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: repl-controller
    name: repl-controller
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: repl-controller
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: repl-controller
      spec:
        containers:
        - env:
          - name: CASSANDRA_SEED
            value: cassandra-0.cassandra:9042
          - name: HDFS_AUTHORITY
            value: hdfs-0.hdfs:9000
          - name: KAFKA_BROKERS
            value: kafka-0.kafka:9093
          - name: HDFS_QUORUM
            value: zk-0.zk:2181
          - name: LOG_LEVEL
            value: INFO
          image: proxima/example-replication-controller:latest #<-- change me
          imagePullPolicy: IfNotPresent # <-- change to Always
          name: repl-controller
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
kind: List
metadata: {}
